config/routes.rb
Rails.application.routes.draw do
  resources :todos
  resources :users, only: [:new, :create]
  get '/login', to: 'sessions#new'           
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :user 
end

app/models/user.rb
class User < ActiveRecord::Base
   has_secure_password
   has_many :todos
 end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # 定义两个 helper 方法，可以在 view 中引用
  helper_method :current_user, :logined?

  def login_as(user)
    session[:user_id] = user.id
    @current_user = user
  end

  # 如果 current_user 方法返回 nil，则说明没有登录
  def logined?
    current_user != nil
  end

  def current_user
    @current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      login_as user
      flash[:notice] = "登陆成功"
      redirect_to todos_path
    else
      flash[:error] = "用户名或密码错误"
      render :new
    end
  end
  
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :authenticate!

  def index
    @todos = @current_user.todos
   @todo= Todo.new
 end

 private
  def authenticate!
    @current_user = User.find_by(id: session[:user_id])
    if @current_user.blank?
      redirect_to login_path and return
    end
  end

end

  def show
  end

  def new
    @todo = Todo.new
  end

def create
  todo = Todo.new(todo_params)
  todo.user_id = @current_user.id
  if todo.save!
    redirect_to todos_path
  end
end

  def destroy
    todo = Todo.find params[:id]
    if todo.destroy
      redirect_to todos_path
    end
  end

  def update
    todo = Todo.find params[:id]
    todo.update todo_params
    redirect_to todos_path
  end

  def edit
    @todo =Todo.find params[:id]
  end
  private
  def todo_params
    todo_params = params.require(:todo).permit(:title,:finished)
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new
    @user.attributes = user_params
    if @user.save
      redirect_to login_path, notice: "注册成功，请登陆"
    else
      flash[:error] = "用户信息填写有误"
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="page">
      <div class="user_info">
        <% if logined? %>
          <span class="username"><%= current_user.username %></span> <%= link_to "退出", logout_path, method: :delete %>
        <% else %>
          <%= link_to "登陆", login_path %> <%= link_to "注册", new_user_path %>
        <% end %>
      </div>
      <div class="header box">
        <h1><a href="/">Todo List</a></h1>
      </div> <!-- header end -->

<%= yield %>
<div class="foot">
  Copyright &copy; <a href="http://codingirls.club" target="_blank">CGC <%= image_tag("rails.png") %></a>
</div> <!-- footer end -->
</div> <!-- page end -->
</body>
</html>

app/views/todos/create.html.erb
<h1>Todos#create</h1>
<p>Find me in app/views/todos/create.html.erb</p>

app/views/todos/destroy.html.erb
<h1>Todos#destroy</h1>
<p>Find me in app/views/todos/destroy.html.erb</p>

app/views/todos/edit.html.erb
<div class="box post">
  <h2>添加</h2>
  <%= form_for @todo do |f| %>
   <p> <%= f.text_field :title, class: 'long_txt' %> </p>
   <p> <%= f.submit"提交", class: 'submit' %> </p>
  <% end %>
</div>

app/views/todos/index.html.erb
<<div class="main box">
  <div class="box todos">
    <h2 class="box">待办事项</h2>
    <ul>
      <% @todos.each do |todo| %>
        <li>
          <% if todo.finished %>
            <del><%= todo.title %></del>
          <% else %>
            <%= todo.title %>
          <% end %>
          <span class="timeinfo"><%= todo.created_at.to_formatted_s(:db) %></span>

          <% if todo.finished %>
            <%= link_to "取消", todo_path(todo.id, todo: {finished: false}), method: :patch %>,
          <% else %>
            <%= link_to "完成", todo_path(todo.id, todo: {finished: true}), method: :patch %>,
          <% end %>

          <%= link_to "编辑", edit_todo_path(todo.id) %>,
          <%= link_to "删除", todo_path(todo.id), method: :delete %>
        </li>
      <% end %>
    </ul>
  </div>

  <div class="box post">
    <h2>添加</h2>
    <%= form_for @todo do |f| %>
      <p> <%= f.text_field :title, class: 'long_txt' %> </p >
      <p> <%= f.submit "提交", class: 'submit' %> </p >
    <% end %>
  </div>

</div> <!— main end —>

app/views/todos/new.html.erb
<div class="box post">
  <h2>添加</h2>
  <%= form_for @todo do |f| %>
   <p> <%= f.text_field :title, class: 'long_txt' %> </p>
   <p> <%= f.submit"提交", class: 'submit' %> </p>
  <% end %>
</div>

app/views/todos/show.html.erb
<h1>Todos#show</h1>
<p>Find me in app/views/todos/show.html.erb</p>

app/views/todos/update.html.erb
<h1>Todos#update</h1>
<p>Find me in app/views/todos/update.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<div class="box post">
  <!-- 显示错误信息 -->
  <% if flash[:notice] %>
    <p class="box notice"> <%= flash[:notice] %> </p>
  <% elsif flash[:error] %>
    <p class="box error"> <%= flash[:error] %> </p>
  <% end %>

  <!-- 用户注册的表格 -->
  <div class="account">
    <h3>用户注册</h3>
    <%= form_for @user do |f| %>
    <p><label>　用户名: </label><%= f.text_field :username %></p>
    <p><label>　　密码: </label><%= f.password_field :password %></p>
    <p><label>确认密码: </label><%= f.password_field :password_confirmation %></p>
    <p><%= f.submit "注册" %></p>
    <p><%= link_to "已有账号？快来登陆", login_path %></p>
    <% end %>
  </div>
</div>